import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:flutter/services.dart';

import '../models/save_data.dart';

/// Sound keys, section 11.1.
class Sfx {
  static const String pickup = 'pickup';
  static const String place = 'place';
  static const String invalid = 'invalid';
  static const String combo = 'combo';
  static const String booster = 'booster';
  static const String ink = 'ink';
  static const String star = 'star';
  static const String levelWin = 'level_win';
  static const String levelFail = 'level_fail';
  static const String blub = 'blub';
  static const String tap = 'tap';

  /// `clear_1` .. `clear_8`, the same sample pitched up a semitone each step.
  static String clear(int step) => 'clear_${step.clamp(1, 8)}';
}

class Music {
  static const String menu = 'music_menu';
  static const String game = 'music_game';
}

/// A preloaded pool of players. Never construct a player per sound.
///
/// Every play is guarded: the audio assets are sourced separately (CC0 or
/// commissioned, never extracted from a reference game) and the game has to
/// run correctly before they land.
class AudioService {
  AudioService._();

  static final AudioService instance = AudioService._();

  static const int _poolSize = 6;
  final List<AudioPlayer> _pool = <AudioPlayer>[];
  int _next = 0;

  AudioPlayer? _music;

  /// What is actually playing right now, and what the app last asked for.
  ///
  /// These are separate on purpose. Turning music off has to stop the player
  /// without forgetting which track belongs on this screen, otherwise turning
  /// it back on leaves the game silent until the player happens to navigate
  /// somewhere that asks for a track again.
  String? _currentMusic;
  String? _desiredMusic;

  /// Consecutive failures per sound, not a permanent blacklist.
  ///
  /// This used to be a `Set` that a single caught exception added to forever,
  /// which made any transient hiccup - the backend busy, a player still
  /// tearing down a previous clip, focus briefly denied - silence that sound
  /// for the rest of the session with no way back but restarting the app.
  /// A genuinely absent asset still fails every attempt and gets given up on
  /// after [_giveUpAfter] cheap tries; anything that recovers, recovers.
  final Map<String, int> _failures = <String, int>{};
  static const int _giveUpAfter = 3;

  GameSettings _settings = GameSettings();
  bool _ready = false;

  /// Guards against two music requests overlapping: the later one wins, and
  /// the earlier one must not write its result over it.
  int _musicToken = 0;

  bool _givenUpOn(String key) => (_failures[key] ?? 0) >= _giveUpAfter;

  void _noteFailure(String key) => _failures[key] = (_failures[key] ?? 0) + 1;

  void _noteSuccess(String key) => _failures.remove(key);

  @visibleForTesting
  int failureCountFor(String key) => _failures[key] ?? 0;

  @visibleForTesting
  bool isSilencedForTesting(String key) => _givenUpOn(key);

  @visibleForTesting
  void debugFailTimes(String key, int times) {
    for (var i = 0; i < times; i++) {
      _noteFailure(key);
    }
  }

  /// Resets everything a test could have left behind. The service is a
  /// singleton, so without this one test's state leaks into the next.
  @visibleForTesting
  void debugReset() {
    _failures.clear();
    _currentMusic = null;
    _desiredMusic = null;
    _musicToken = 0;
    _settings = GameSettings();
  }

  /// Music ducks to 40% while any SFX is playing.
  static const double _duckedVolume = 0.4;
  DateTime _duckUntil = DateTime.fromMillisecondsSinceEpoch(0);

  /// The player's music slider is the ceiling for everything music related.
  double get _musicVolume => _settings.musicVolume;

  /// The shipped audio is generated by `tool/generate_audio.dart` as WAV,
  /// because encoding OGG or M4A needs a codec pure Dart does not have. When
  /// commissioned audio lands, drop OGG/M4A files with the same names into
  /// `assets/audio` and restore the per-platform extension:
  ///
  ///     !kIsWeb && Platform.isIOS ? 'm4a' : 'ogg'
  ///
  /// Both platforms decode WAV natively, so nothing else has to change.
  String get _ext => 'wav';

  Future<void> init(GameSettings settings) async {
    _settings = settings;
    if (_ready) return;
    _ready = true;
    try {
      for (var i = 0; i < _poolSize; i++) {
        final p = AudioPlayer(playerId: 'sfx_$i');
        await p.setReleaseMode(ReleaseMode.stop);
        _pool.add(p);
      }
    } catch (_) {
      // No audio backend, for instance under `flutter test`. Play calls below
      // guard on an empty pool and stay silent.
      _pool.clear();
    }
  }

  void updateSettings(GameSettings settings) {
    _settings = settings;
    // Touching a sound control is the clearest possible statement that the
    // player wants to hear something, so it also clears the give-up counters.
    // Anything that failed earlier gets a fresh chance here rather than
    // staying dead until the app is restarted.
    _failures.clear();

    if (!settings.music) {
      stopMusic();
      return;
    }
    final music = _music;
    // `_currentMusic` is what we believe; `music.state` is what is true. They
    // drift when a loop ends or the backend drops the track underneath us, and
    // believing the wrong one is what leaves the game silent until a restart.
    final playing =
        music != null &&
        (music.state == PlayerState.playing ||
            music.state == PlayerState.paused);
    if (_currentMusic == null || !playing) {
      // Off to on, never started, stranded by a failure, or the track died.
      final want = _desiredMusic;
      if (want != null) {
        _currentMusic = null;
        playMusic(want);
      }
      return;
    }
    // Genuinely playing: move the volume on the live player rather than
    // restarting the track, so dragging the slider does not stutter the loop.
    unawaited(_setMusicVolume(music, _musicVolume));
  }

  /// Fire and forget by design: nothing in the game can act on the result of
  /// a sound, and returning a Future would only invite call sites to await a
  /// frame on the audio backend.
  void play(String key, {double volume = 1}) => unawaited(_play(key, volume));

  Future<void> _play(String key, double volume) async {
    if (!_settings.sfx || _pool.isEmpty || _givenUpOn(key)) return;
    // The per-call volume is the sound's place in the mix; the slider is the
    // player's ceiling over the whole mix. They multiply.
    final level = volume * _settings.sfxVolume;
    if (level <= 0) return;
    final player = _pool[_next = (_next + 1) % _pool.length];
    try {
      await player.stop();
      await player.setVolume(level);
      await player.play(AssetSource('audio/$key.$_ext'));
      _noteSuccess(key);
      _duck();
    } catch (_) {
      _noteFailure(key);
    }
  }

  /// The pitch ladder, section 11.2.
  ///
  /// One sound per line with a 70ms stagger, each step one rung higher, so
  /// three lines at once read as a rising arpeggio.
  void playClearLadder(int clearStreak, int lines) =>
      unawaited(_clearLadder(clearStreak, lines));

  Future<void> _clearLadder(int clearStreak, int lines) async {
    if (!_settings.sfx) return;
    for (var i = 0; i < lines; i++) {
      final step = (clearStreak + i).clamp(1, 8);
      play(Sfx.clear(step));
      if (i < lines - 1) {
        await Future<void>.delayed(const Duration(milliseconds: 70));
      }
    }
    if (clearStreak >= 3) play(Sfx.combo, volume: 0.7);
  }

  /// The three star sounds on the result screen, 220ms apart.
  void playStars(int stars) => unawaited(_stars(stars));

  Future<void> _stars(int stars) async {
    for (var i = 0; i < stars; i++) {
      play(Sfx.star, volume: 0.9);
      await Future<void>.delayed(const Duration(milliseconds: 220));
    }
  }

  void playMusic(String key) => unawaited(_playMusic(key));

  Future<void> _playMusic(String key) async {
    // Remembered even when nothing can play it, so that enabling music later
    // knows what to start.
    _desiredMusic = key;
    // An AudioPlayer registers an event channel on construction, and that
    // channel throws asynchronously when no plugin is registered - outside any
    // try/catch here. An empty pool means init() found no audio backend, so
    // never construct a player at all in that case.
    if (_pool.isEmpty) return;
    if (!_settings.music || _givenUpOn(key)) return;
    if (_currentMusic == key) return;

    final token = ++_musicToken;
    try {
      _music ??= AudioPlayer(playerId: 'music');
      await _music!.setReleaseMode(ReleaseMode.loop);
      await _music!.setVolume(_musicVolume);
      await _music!.play(AssetSource('audio/$key.$_ext'));
      if (token != _musicToken) return; // a later request took over
      // Recorded only once the track really started. Setting it up front left
      // the service believing music was playing after a failure, so every
      // later request short circuited and the game stayed silent.
      _currentMusic = key;
      _noteSuccess(key);
    } catch (_) {
      if (token != _musicToken) return;
      _noteFailure(key);
      _currentMusic = null;
    }
  }

  /// Holds the current track where it is. Used by the pause overlay.
  ///
  /// Deliberately not [stopMusic]: stopping forgets the play position, so
  /// resuming would restart the loop from the top every time the player pauses
  /// to think. `_currentMusic` stays set, because a paused track is still the
  /// track that belongs on this screen.
  void pauseMusic() {
    final music = _music;
    if (music == null || _currentMusic == null) return;
    try {
      unawaited(music.pause());
    } catch (_) {
      // Nothing playing; `resumeMusic` starts from scratch instead.
      _currentMusic = null;
    }
  }

  /// The other half of [pauseMusic]. Falls back to starting the desired track
  /// from the beginning when there is nothing to resume, which is what happens
  /// if the player turned music off and on again while paused.
  void resumeMusic() {
    if (!_settings.music) return;
    final music = _music;
    if (music == null || _currentMusic == null) {
      final want = _desiredMusic;
      if (want != null) playMusic(want);
      return;
    }
    try {
      unawaited(music.resume());
    } catch (_) {
      _currentMusic = null;
    }
  }

  void stopMusic() {
    // `_desiredMusic` deliberately survives: it is what the screen wants, and
    // turning music back on has to know what to restart.
    _currentMusic = null;
    _musicToken++;
    final music = _music;
    try {
      if (music != null) unawaited(music.stop());
    } catch (_) {
      // Nothing playing.
    }
  }

  /// Moves the live music player's volume, and treats a failure as "the player
  /// is no longer in a state I understand" rather than ignoring it: leaving
  /// `_currentMusic` set after a failed call is what stranded the music with
  /// no way to restart it.
  Future<void> _setMusicVolume(AudioPlayer music, double level) async {
    try {
      await music.setVolume(level);
    } catch (_) {
      _currentMusic = null;
    }
  }

  void _duck() {
    _duckUntil = DateTime.now().add(const Duration(milliseconds: 260));
    final music = _music;
    if (music == null || _currentMusic == null) return;
    unawaited(_setMusicVolume(music, _duckedVolume * _musicVolume));
    Future<void>.delayed(const Duration(milliseconds: 280), () {
      if (DateTime.now().isAfter(_duckUntil)) {
        unawaited(_setMusicVolume(music, _musicVolume));
      }
    });
  }

  Future<void> disposeAll() async {
    for (final p in _pool) {
      await p.dispose();
    }
    _pool.clear();
    await _music?.dispose();
    _music = null;
    _ready = false;
  }
}

/// Section 10.4. Respects the settings toggle.
class Haptics {
  static GameSettings settings = GameSettings();

  static void light() {
    if (settings.haptics) HapticFeedback.lightImpact();
  }

  static void medium() {
    if (settings.haptics) HapticFeedback.mediumImpact();
  }

  static void heavy() {
    if (settings.haptics) HapticFeedback.heavyImpact();
  }

  static void selection() {
    if (settings.haptics) HapticFeedback.selectionClick();
  }
}
